#   _______  _______ _________ _______  _______  _______  _______  _______
#  (  ____ \(  ___  )\__   __/(  ___  )(  ____ \(  ___  )(  ____ )(  ____ \
#  | (    \/| (   ) |   ) (   | (   ) || (    \/| (   ) || (    )|| (    \/
#  | |      | (___) |   | |   | (___) || |      | |   | || (____)|| (__
#  | | ____ |  ___  |   | |   |  ___  || |      | |   | ||     __)|  __)
#  | | \_  )| (   ) |   | |   | (   ) || |      | |   | || (\ (   | (
#  | (___) || )   ( |___) (___| )   ( || (____/\| (___) || ) \ \__| (____/\
#  (_______)|/     \|\_______/|/     \|(_______/(_______)|/   \__/(_______/
#GaiaCore config file

mysql:
  url: 'jdbc:mysql://localhost:3306/DBName' #jdbc:mysql://URL/Server_Db_name
  username: 'Gaia'
  password: 'p4ssw0rd'